version: "3.8"

services:
  driver:
    build: jupyter
    user: jovyan
    ports:
      - 4040:4040
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - notebooks:/home/jovyan/notebooks
      - data:/home/jovyan/data
      - checkpoint:/home/jovyan/checkpoint

  master:
    build: ./spark
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_DAEMON_MEMORY=2G
      - SPARK_MASTER_OPTS="-Dspark.deploy.defaultCores=1"
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - data:/home/jovyan/data
      - checkpoint:/home/jovyan/checkpoint

  worker_1:
    build: ./spark
    user: root
    depends_on:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8081:8081
    volumes:
      - data:/home/jovyan/data
      - checkpoint:/home/jovyan/checkpoint

  worker_2:
    build: ./spark
    user: root
    depends_on:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8082:8081
    volumes:
      - data:/home/jovyan/data
      - checkpoint:/home/jovyan/checkpoint

  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9093,LISTENER_DOCKER_EXTERNAL://${EXTERNAL_ADDRESS}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  checkpoint:
    driver_opts:
      type: none
      device: ./checkpoint
      o: bind

  data:
    driver_opts:
      type: none
      device: ./data
      o: bind

  notebooks:
    driver_opts:
      type: none
      device: ./notebooks
      o: bind
